### PR TITLE
go/tools/builders: Pass `CFLAGS` to assembly sources compilation

### LINKED ISSUE #4558: CGO-enabled cross-compilation of assembly sources fails with custom LLVM toolchain
When Bazel is configured with a custom LLVM toolchain, CGO cross-compilation of assembly sources fails with an `unknown file type` error.

A minimal reproduction is as follows:

`go.mod`:

```
module repro

go 1.25.7

require github.com/DataDog/zstd v1.5.7
```

`main.go`:

```
package main

import (
    _ "github.com/DataDog/zstd"
)

func main() {}
```

`BUILD.bazel`:

```
load("@io_bazel_rules_go//go:def.bzl", "go_binary")

go_binary(
    name = "repro",
    srcs = ["main.go"],
    importpath = "repro",
    deps = ["@com_github_datadog_zstd//:zstd"],
)
```

`MODULE.bazel`:

```
bazel_dep(name = "rules_go", version = "0.60.0")

go_sdk = use_extension("@rules_go//go:extensions.bzl", "go_sdk")
go_sdk.from_file(go_mod = "//:go.mod")

bazel_dep(name = "gazelle", version = "0.47.0")

go_deps = use_extension("@gazelle//:extensions.bzl", "go_deps")
go_deps.from_file(go_mod = "//:go.mod")
use_repo(
    go_deps,
    "com_github_datadog_zstd",
)

bazel_dep(name = "toolchains_llvm", version = "1.6.0")

llvm = use_extension("@toolchains_llvm//toolchain/extensions:llvm.bzl", "llvm", dev_dependency = True)
llvm.toolchain(
    name = "llvm_toolchain",
    extra_link_flags = {"linux-x86_64": ["-no-pie"]},
    extra_llvm_distributions = {
        "LLVM-20.1.4-Linux-ARM64.tar.xz": "4de80a332eecb06bf55097fd3280e1c69ed80f222e5bdd556221a6ceee02721a",
        "LLVM-20.1.4-Linux-X64.tar.xz": "113b54c397adb2039fa45e38dc8107b9ec5a0baead3a3bac8ccfbb65b2340caa",
        "LLVM-20.1.4-macOS-ARM64.tar.xz": "debb43b7b364c5cf864260d84ba1b201d49b6460fe84b76eaa65688dfadf19d2",
        "clang+llvm-20.1.4-x86_64-pc-windows-msvc.tar.xz": "2b12ac1a0689e29a38a7c98c409cbfa83f390aea30c60b7a06e4ed73f82d2457",
    },
    llvm_version = "20.1.4",
)
llvm.sysroot(
    name = "llvm_toolchain",
    label = "@sysroot//:sysroot",
    targets = ["linux-x86_64"],
)
use_repo(llvm, "llvm_toolchain")

register_toolchains(
    "@llvm_toolchain//:all",
    dev_dependency = True,
)
```

The LLVM sysroot was created by extracting the root filesystem from a Ubuntu container.

```
$ docker run --platform linux/amd64 --rm -it ubuntu:24.04
# apt-get update
# apt-get install build-essential
# rm -rf /var/lib/dpkg/info
```

```
$ mkdir /tmp/ubuntu
$ cd /tmp/ubuntu
$ docker export <container ID> | tar xvz
$ touch MODULE.bazel
$ touch BUILD.bazel
```

Contents of `/tmp/ubuntu/BUILD.bazel`:

```
filegroup(
    name = "sysroot",
    srcs = glob(["**"]),
    visibility = ["//visibility:public"],
)
```

On a `darwin/arm64` host platform, the following invocation results in an error:

```
$ bazel build --platforms=@rules_go//go/toolchain:linux_amd64_cgo --inject_repository=sysroot=/tmp/ubuntu :repro
```

```
INFO: Invocation ID: af3bf7dd-d622-4c80-85d4-b86511a41408
INFO: Analyzed target //:repro (77 packages loaded, 9079 targets configured).
ERROR: /Users/.../.cache/bazel/92410d0e3373f265902564b48493ac12/external/gazelle++go_deps+com_github_datadog_zstd/BUILD.bazel:3:11: GoCompilePkg external/gazelle++go_deps+com_github_datadog_zstd/zstd.a failed: (Exit 1): builder failed: error executing GoCompilePkg command (from go_library rule target @@gazelle++go_deps+com_github_datadog_zstd//:zstd) bazel-out/darwin_arm64-opt-exec/bin/external/rules_go++go_sdk+main___download_0/builder_reset/builder compilepkg -sdk external/rules_go++go_sdk+main___download_0 -goroot ... (remaining 227 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
ld.lld: error: /var/folders/r5/nn1y53zn451bvq6pyghmprt00000gn/T/rules_go_work-1495819361/cgo/github.com/DataDog/zstd/_x46.o: unknown file type
clang: error: linker command failed with exit code 1 (use -v to see invocation)
compilepkg: error running subcommand external/toolchains_llvm++llvm+llvm_toolchain/bin/cc_wrapper.sh: exit status 1
Target //:repro failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 19.483s, Critical Path: 16.14s
INFO: 5 processes: 5 action cache hit, 2 disk cache hit, 3 internal.
ERROR: Build did NOT complete successfully
```

Note that the dependency is somewhat arbitrary; `github.com/DataDog/zstd` contains assembly files, and was convenient for the reproduction case.

The root cause appears to be that, in the C compilation invocation of CGO sources, all flags are omitted for assembly sources:

https://github.com/bazel-contrib/rules_go/blob/v0.60.0/go/tools/builders/cgo2.go#L222

Passing all copts (as is done for `cSrcs`) exposes custom flags like `--sysroot` configured by the custom LLVM toolchain, which allows the cross-compilation to work.

### PR DESCRIPTION
**Pull request by LINKIWI**
**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**

This PR passes C flags to the invocation of the assembly compiler when CGO is enabled.

**Which issues(s) does this PR fix?**

Fixes #4558

**Other notes for review**

* Please refer to the issue for a reproduction case.
* This PR includes a test case that directly exercises the fix, but does not attempt to reconstruct the convoluted setup that originally exposed the bug.

### CODE REVIEW

File: go/tools/builders/cgo2.go [hunk 1]
```diff
@@ -331,7 +331,7 @@ func compileCSources(goenv *env, cSrcs, cxxSrcs, objcSrcs, objcxxSrcs, sSrcs, hS
 		{cxxSrcs, combineFlags(cppFlags, hdrIncludes, cxxFlags, defaultCFlags)},
 		{objcSrcs, combineFlags(cppFlags, hdrIncludes, objcFlags, defaultCFlags)},
 		{objcxxSrcs, combineFlags(cppFlags, hdrIncludes, objcxxFlags, defaultCFlags)},
-		{sSrcs, nil},
+		{sSrcs, combineFlags(cppFlags, hdrIncludes, cFlags, defaultCFlags)},
```
Comment (fmeum) [inline go/tools/builders/cgo2.go]: Are `hdrIncludes` needed here?

Comment (LINKIWI) [reply go/tools/builders/cgo2.go]: I don't think so. Removed.

**Comment by LINKIWI** [comment]
Hi @fmeum are we ok to continue here? Any smoke tests you recommend we run for this? Thanks.
