### PR TITLE
Making gopackagesdriver correctly handle relative queries made from a subdirectory.

### LINKED ISSUE #4001: gopackagesdriver does not handle relative queries correctly when run from a subdirectory of the workspace
### What version of rules_go are you using?

Reproduced this on master of https://github.com/bazelbuild/rules_go which as of the time of this writing was at this commit: https://github.com/bazelbuild/rules_go/commit/86a7f025d2fc052ab6154603b481cb7e4419598f

### What version of gazelle are you using?

0.34.0

### What version of Bazel are you using?

7.2.1

### Does this issue reproduce with the latest releases of all the above?

N/A, found this on master of rules_go

### What operating system and processor architecture are you using?

Mac OS

### Any other potentially useful information about your toolchain?

N/A

### What did you do?

This was discovered while I was trying to setup rules_go gopackagedriver with VSCode IDE for a project I work on. In our usecase we work on a big monorepo and projects are subdirectories of that monorepo. The workspace structure looks like this:
```
WORKSPACE
project1/BUILD.bazel
project1/main.go
project2/BUILD.bazel
project2/main.go
...
```

The script I setup in vscode looked like this:
```
#!/usr/bin/env bash
exec bazel run --tool_tag=gopackagesdriver -- @io_bazel_rules_go//go/tools/gopackagesdriver "${@}"
```

When working on one of the projects, let's say project1, we setup VSCode to only open project1 folder (and therefore the script above would run with working directory being project1. While working on it, gopackagedriver had to respond to the following queries:
```
./... builtin
file=/the/absolute/path/to/project1/main.go
```

I expected the first query involving `./...` to only return results from project1, but instead it returned stuff for @//:stdlib. Playing with it I also noticed that it did not work as expected for other relative queries like file=./main.go . While my VSCode setup does not send those queries I would have expected them to work and may impact people working on other tools/IDEs.

I was able to reproduce this within https://github.com/bazelbuild/rules_go itself. First to setup:
```
mkdir -p /tmp/tests &&
cd /tmp/tests &&
git clone https://github.com/bazelbuild/rules_go &&
cd rules_go &&
git checkout 86a7f025d2fc052ab6154603b481cb7e4419598f
```

Then ran the following test cases:
A) `(cd go/tools/gopackagesdriver; echo {} | bazel run //go/tools/gopackagesdriver -- ./...)`
B) `(cd go/tools/gopackagesdriver; echo {} | bazel run //go/tools/gopackagesdriver -- file=main.go)`

### What did you expect to see?

A) Should return results based on packages in //go/tools/gopackagesdriver/...  (which only has  //go/tools/gopackagesdriver:gopackagesdriver_lib)
B) Should return results based on the package that contains go/tools/gopackagesdriver/main.go (which is //go/tools/gopackagesdriver:gopackagesdriver_lib)

### What did you see instead?

A) targets based on `kind("^(go_library) rule$", ...)]` which is all go_library in the repository rather the ones in the subdirectory go/tools/gopackagesdriver
```
% (cd go/tools/gopackagesdriver; echo {} | bazel run //go/tools/gopackagesdriver -- ./...)
Starting local Bazel server and connecting to it...
INFO: Analyzed target //go/tools/gopackagesdriver:gopackagesdriver (67 packages loaded, 9988 targets configured).
INFO: Found 1 target...
Target //go/tools/gopackagesdriver:gopackagesdriver up-to-date:
  bazel-bin/go/tools/gopackagesdriver/gopackagesdriver_/gopackagesdriver
INFO: Elapsed time: 35.072s, Critical Path: 19.81s
INFO: 10 processes: 6 internal, 4 darwin-sandbox.
INFO: Build completed successfully, 10 total actions
INFO: Running command line: bazel-bin/go/tools/gopackagesdriver/gopackagesdriver_/gopackagesdriver ./...
Running: [bazel info --tool_tag=gopackagesdriver --ui_actions_shown=0]
Running: [bazel query --tool_tag=gopackagesdriver --ui_actions_shown=0 --consistent_labels --ui_event_filters=-info,-stderr --noshow_progress --order_output=no --output=label --nodep_deps --noimplicit_deps --notool_deps kind("^(go_library) rule$", ...)]
Running: [bazel build --tool_tag=gopackagesdriver --ui_actions_shown=0 --show_result=0 --build_event_json_file=/var/folders/qx/6819xgwx62d9jkkh7nlzgc9m0000gp/T/gopackagesdriver_bep_1791540436 --build_event_json_file_path_conversion=no --experimental_convenience_symlinks=ignore --ui_event_filters=-info,-stderr --noshow_progress --aspects=@//go/tools/gopackagesdriver:aspect.bzl%go_pkg_info_aspect --output_groups=go_pkg_driver_json_file,go_pkg_driver_stdlib_json_file,go_pkg_driver_srcs --keep_going --target_pattern_file=/var/folders/qx/6819xgwx62d9jkkh7nlzgc9m0000gp/T/gopackagesdriver_targets_3746790315]
{"NotHandled":false,"Compiler":"gc","Arch":"arm64","Roots":["@//tests/core/go_test/x_defs:foo","@//tests/core/cross:platform_lib",
```

B) Targets based on the `kind("^(go_library|go_test|go_binary) rule$", same_pkg_direct_rdeps("main.go"))` query and an error.
```
% (cd go/tools/gopackagesdriver; echo {} | bazel run //go/tools/gopackagesdriver -- file=main.go)
INFO: Analyzed target //go/tools/gopackagesdriver:gopackagesdriver (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //go/tools/gopackagesdriver:gopackagesdriver up-to-date:
  bazel-bin/go/tools/gopackagesdriver/gopackagesdriver_/gopackagesdriver
INFO: Elapsed time: 0.285s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/go/tools/gopackagesdriver/gopackagesdriver_/gopackagesdriver 'file=main.go'
Running: [bazel info --tool_tag=gopackagesdriver --ui_actions_shown=0]
Running: [bazel query --tool_tag=gopackagesdriver --ui_actions_shown=0 --consistent_labels --ui_event_filters=-info,-stderr --noshow_progress --order_output=no --output=label --nodep_deps --noimplicit_deps --notool_deps kind("^(go_library|go_test|go_binary) rule$", same_pkg_direct_rdeps("main.go"))]
ERROR: no such target '//:main.go': target 'main.go' not declared in package '' defined by /private/tmp/tests/rules_go/BUILD.bazel
error: unable to lookup package: query failed: unable to query: bazel query failed: exit status 7%
```

### PR DESCRIPTION
**Pull request by waltercacau**
**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**

It allows gopackagesdriver to be called within a subdirectory of a workspace and properly resolve queries from gopls from IDEs like VSCode when they include relative references. For example, if you have the following repo/workspace structure:
```
WORKSPACE
project1/BUILD.bazel
project1/main.go
project2/BUILD.bazel
project2/main.go
...
```

If you run gopackagesdriver using bazel run from project1 directory and receive the following queries:
```
file=./main.go
./...
```
The existing code will try to resolve those queries against the root of the workspace, when instead we would expect it to resolve relative to the project1 directory.

**Which issues(s) does this PR fix?**

Fixes #4001 

**Other notes for review**

### CODE REVIEW

File: go/tools/gopackagesdriver/bazel_json_builder.go [hunk 1]
```diff
@@ -107,6 +97,20 @@ func (b *BazelJSONBuilder) localQuery(request string) string {
...
 
+func (b *BazelJSONBuilder) adjustToRelativePathIfPossible(request string) string {
+	// If request is a relative path and gopackagesdriver is ran within a subdirectory of the
+	// workspace, we must first resolve the absolute path for it.
+	// Note: Using FromSlash/ToSlash for handling windows
+	absRequest := filepath.FromSlash(request)
+	if !filepath.IsAbs(absRequest) {
+		absRequest = filepath.Join(b.bazel.BuildWorkingDirectory(), absRequest)
+	}
+	if relPath, err := filepath.Rel(workspaceRoot, absRequest); err == nil {
```
Comment (fmeum) [inline go/tools/gopackagesdriver/bazel_json_builder.go:108]: What would be a possible error case here? Should we log it?

File: go/tools/gopackagesdriver/bazel_json_builder.go [hunk 2]
```diff
@@ -93,12 +88,7 @@ func (b *BazelJSONBuilder) getKind() string {
 }
 
 func (b *BazelJSONBuilder) localQuery(request string) string {
-	request = path.Clean(request)
-	if filepath.IsAbs(request) {
-		if relPath, err := filepath.Rel(workspaceRoot, request); err == nil {
-			request = relPath
-		}
-	}
+	request = path.Clean(b.adjustToRelativePathIfPossible(request))
```
Comment (fmeum) [inline go/tools/gopackagesdriver/bazel_json_builder.go:91]: `filepath.Rel` always returns a clean path, so this wouldn't be necessary if we figure out the error case.

File: go/tools/gopackagesdriver/bazel_json_builder.go (hunk 1 above)
Comment (waltercacau) [reply go/tools/gopackagesdriver/bazel_json_builder.go:108]: I am looking at the code: https://pkg.go.dev/path/filepath#Rel

There seems to be two cases. One is on windows if you give paths on different roots (like c:\a\b z:\y\x, you can't make it relative because you don't share a root. The other case I found is if to resolve you would need th current directory: filepath.Rel("./b/c", "/a"). This would not happen if we could guarantee that both of them are Abs paths.

From what I can tell, bazel sets env BUILD_WORKSPACE_DIRECTORY and BUILD_WORKING_DIRECTORY is absolute already.

Neither case is a likely scenario here, so for now I will follow the suggestion of logging it.

File: go/tools/gopackagesdriver/bazel_json_builder.go (hunk 2 above)
Comment (waltercacau) [reply go/tools/gopackagesdriver/bazel_json_builder.go:91]: also removing the clean given it is very unlikely for us to reach the error scenario here

**Review by fmeum — APPROVED** [review]
@JamyDev Could you also take a look?

**Review by JamyDev — APPROVED** [review]

**Comment by JamyDev** [comment]
LGTM!

**Comment by JamyDev** [comment]
I'll validate it with Uber code on Monday, but I don't expect it to be breaking.

**Comment by waltercacau** [comment]
Hi there, just checking in, is this PR good to merge?

**Comment by fmeum** [comment]
@JamyDev I'll merge this now as it looks safe, but please let me know if you discover any issues with it.
