### PR TITLE
go_test: Add env attribute

### LINKED ISSUE #2921: no such attribute 'env' in 'go_transition_test' rule
### rules_go version

`v0.27.0`

### What version of gazelle are you using?

`v0.23.0`

### What version of Bazel are you using?

`4.1.0`

### Does this issue reproduce with the latest releases of all the above?

Reproduces with `v0.28.0`

### What operating system and processor architecture are you using?

macOS, amd64.

### Any other potentially useful information about your toolchain?

Fairly standard toolchain, using a few custom protobuf compilers for proto+gRPC. This is a set of e2e (external) tests that uses the _actual_ binary as a run-time dependency.

### What did you do?
```
go_test(
    name = "go_default_test",
    srcs = ["svm_test.go"],
    args = ["$(location :svm)"], # actual binary under test
    data = [
        ":svm",
        "//thirdparty/patchcli",
    ],
    embed = [":go_default_library"],
    env = {
        "SNIPPED_TOOL_PATH": "$(location //thirdparty/snipped_tool)",
    },
    race = "off",
    rundir = ".",
    tags = [
        "functional",
    ],
    deps = ["<snip>"],
)
```
```
load("@bazel_skylib//rules:native_binary.bzl", "native_binary")

native_binary(
    name = "snipped_tool",
    src = select({
        "@platforms//os:windows": ":win64",
        "@platforms//os:macos": ":macos",
        "@platforms//os:linux": ":linux",
    }),
    out = "snipped_tool",
)
```

`$ bazel test //services/svm:go_default_test`

### What did you expect to see?

Per [the Bazel common attributes](https://docs.bazel.build/versions/main/be/common-definitions.html#common-attributes-tests), I would expect this to work and this environment variable be available in the test runtime.

### What did you see instead?

```
$ bazel test //services/svm:go_default_test
Another command (pid=42199) is running. Waiting for it to complete on the server (server_pid=39418)...
INFO: Invocation ID: de25d398-863c-4243-9b98-697aea4a6cc5
ERROR: /Users/jhoward/git/patcher/services/svm/BUILD.bazel:61:8: //services/svm:go_default_test: no such attribute 'env' in 'go_transition_test' rule
ERROR: error loading package 'services/svm': Package 'services/svm' contains errors
INFO: Elapsed time: 31.567s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
FAILED: Build did NOT complete successfully (1 packages loaded)
```

### PR DESCRIPTION
**Pull request by illicitonion**
**What type of PR is this?**

Feature

**What does this PR do? Why is it needed?**

This allows setting environment variables before static initialisers
run, and which reference expanded locations.

**Which issues(s) does this PR fix?**

Partially fixes #2921

### CODE REVIEW

**Comment by illicitonion** [comment]
I think this is ready for review :)

/cc @linzhp @robfig

**Comment by blico** [comment]
Thanks for working on this @illicitonion. 

My understanding is that we could add support for this attribute using the `TestEnvironment` provider avoiding the need for a wrapper executable around `go_test`. https://docs.bazel.build/versions/main/skylark/lib/testing.html#TestEnvironment.

With this approach, we should just need to run whatever pre-processing is needed on the `env` attr (e.g. `ctx.expand_location`) and then construct a `TestEnvironment` provider and return it through `go_test`. 

It would also be good to add some documentation to the `go_test` rule about the new attr, and some test cases verifying `env` is available during `TestMain` and the contents of `env` are expanded.

File: go/tools/bazel/runfiles.go [hunk 1]
```diff
@@ -51,10 +51,21 @@ func Runfile(path string) (string, error) {
 	}
 
 	// Search manifest if we have one.
-	if entry, ok := runfiles.index[path]; ok {
```
Comment (blico) [inline go/tools/bazel/runfiles.go:54]: Are you sure all of the changes to this file are needed? I patched the change locally and the tests still passed without the changes to this file.

Comment (illicitonion) [reply go/tools/bazel/runfiles.go:54]: Yeah, it's necessary on Windows - the way this works on non-Windows is that first we'll stat the file, see the symlink and be happy.

But the way it works on Windows is we parse a metadata file with paths to files written down, and we do a match based on exactly the file name inside whatever workspace the file happens to be in. These changes are necessary for that runfiles lookup to work properly.

I could, if you'd prefer, make the test use a file in the main workspace (rather than from the `go_sdk` workspace), and send a separate PR fixing up the separate-workspace runfiles lookup issue, but figured fixing it all in one was reasonable...

Comment (blico) [reply go/tools/bazel/runfiles.go:54]: That makes sense, thanks for the clarification. Yeah, I think including the change as part of this PR is reasonable.
