### PR TITLE
Fix go proto library for once and for all

### LINKED ISSUE #173: Generating protos in sub directories fails
I'm trying to use a vendoring/third_party library with a flat BUILD file. The problem I have is that it contains a proto file deep in the tree. It seems fine to create a go_library with source files in sub directories, but protos don't seem to work.

I've made up a simple example. Something like:

```
~/tmp/go-bzl % tree lib 
lib
├── BUILD
└── sub
    └── bar.proto
```

```
~/tmp/go-bzl % cat lib/BUILD                                   
load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:go_proto_library.bzl", "go_proto_library")

go_proto_library(
    name = "sub/bar_proto",  # Also tried name="bar_proto"
    srcs = [
        "sub/bar.proto",
    ],
    visibility = ["//visibility:public"],
)
```

```
~/tmp/go-bzl % bazel build lib:sub/bar_proto                
INFO: Found 1 target...
ERROR: /home/y/tmp/go-bzl/lib/BUILD:20:1: Generating into bazel-out/local-fastbuild/bin/lib/sub/bar_proto/sub failed: linux-sandbox failed: error executing command /home/y/.cache/bazel/_bazel_y/1129aeaeb86f4311cfe08c57d10b52b4/execroot/go-bzl/_bin/linux-sandbox ... (remaining 6 argument(s) skipped).
bazel-out/local-fastbuild/bin/lib/sub/: No such file or directory
Target //lib:sub/bar_proto failed to build
```

I also inspected the sandbox, and it seems that just like the error says, there is no directory bazel-out/local-fastbuild/bin/lib/sub/, and protoc probably just fails when trying to write the proto. Should go_proto_library create the directories for output files? Any other ways to make this work?

Thanks,

### LINKED ISSUE #910: importpath must match path in repo for go_proto_library
For a go_proto_library, if I set importpath to something other than the path in the repo, go_proto_library fails with:

```
ERROR: /usr/local/google/home/rodrigoq/git/bazeltest/diff_importpath/foo/BUILD.bazel:16:1: output 'foo/lib_importpath_bar/bar/foo.pb.go' was not created
```

The rule expects the output at the declared importpath, but protoc appears to generate it based on the path within the repo.

Full repro (bazel 0.6.1):
```
> cat WORKSPACE 
git_repository(
    name = "io_bazel_rules_go",
    commit = "9cf23e2aab101f86e4f51d8c5e0f14c012c2161c",
    remote = "https://github.com/bazelbuild/rules_go.git",
)

load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains", "go_repository")

go_register_toolchains()

go_rules_dependencies()

load("@io_bazel_rules_go//proto:def.bzl", "proto_register_toolchains")

proto_register_toolchains()
> cat BUILD.bazel 
load("@io_bazel_rules_go//go:def.bzl", "go_prefix")

go_prefix("my_go_prefix")
> cat foo/foo.proto 
syntax = "proto3";

package foo;

message Foo {
  string very = 1;
  int32 useful = 2;
}
> cat foo/BUILD.bazel 
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")

proto_library(
    name = "proto",
    srcs = ["foo.proto"],
    visibility = ["//visibility:public"],
)

go_proto_library(
    name = "lib_importpath_foo",
    importpath = "foo",
    proto = ":proto",
    visibility = ["//visibility:public"],
)

go_proto_library(
    name = "lib_importpath_bar",
    importpath = "bar",
    proto = ":proto",
    visibility = ["//visibility:public"],
)
> bazel build foo:lib_importpath_foo
INFO: Analysed target //foo:lib_importpath_foo (0 packages loaded).
INFO: Found 1 target...
Target //foo:lib_importpath_foo up-to-date:
  bazel-bin/foo/~normal~lib_importpath_foo~/foo.a
INFO: Elapsed time: 0.439s, Critical Path: 0.00s
INFO: Build completed successfully, 1 total action
> bazel build -s foo:lib_importpath_bar
INFO: Analysed target //foo:lib_importpath_bar (0 packages loaded).
INFO: Found 1 target...
SUBCOMMAND: # //foo:lib_importpath_bar [action 'Generating into bazel-out/local-fastbuild/bin/foo/lib_importpath_bar/bar']
(cd /usr/local/google/home/rodrigoq/.cache/bazel/_bazel_rodrigoq/42807b98f0f2cce20415d49167562dfe/execroot/__main__ && \
  exec env - \
  bazel-out/host/bin/external/com_github_google_protobuf/protoc '--go_out=:bazel-out/local-fastbuild/bin/foo/lib_importpath_bar/' '--plugin=protoc-gen-go=bazel-out/host/bin/external/com_github_golang_protobuf/protoc-gen-go/protoc-gen-go' --descriptor_set_in bazel-out/local-fastbuild/genfiles/foo/proto-descriptor-set.proto.bin foo/foo.proto)
ERROR: /usr/local/google/home/rodrigoq/git/bazeltest/diff_importpath/foo/BUILD.bazel:16:1: output 'foo/lib_importpath_bar/bar/foo.pb.go' was not created
ERROR: /usr/local/google/home/rodrigoq/git/bazeltest/diff_importpath/foo/BUILD.bazel:16:1: not all outputs were created or valid
Target //foo:lib_importpath_bar failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.531s, Critical Path: 0.07s
FAILED: Build did NOT complete successfully
```

### LINKED ISSUE #1021: go_proto_library fails when go_import_path is not set.
bazel version 0.7.0
rules_go version 0.7.0.
platform: ubuntu-trusty

**Summary**: go_proto_library fails to locate output .pb.go files when go_package_path isn't set.

**Detail**:
There are a number of `go get` repositories which contain .proto files which define package, but not go_package_path.
When imported with go_repository, they fail to build, because `protoc` puts the `.pb.go` output in a different place from where the rule expects to find it.
When I control the source, a work around is setting go_package_path.
The combination makes it difficult to contribute upstream.

This can be reproduced by attempting to build a rule that depends on github.com/njt99/rules_go_missing_pb_go/tiny. I've also tested it at HEAD.

### PR DESCRIPTION
**Pull request by ianthehat**
This uses an aspect to collect up the full set of proto imports and what their
go import path should be, and then hands that to the proto compile line.
It then attempts to map the outputs to the expected outputs by basename.
All of this means that the option go_package lines are not needed for a correct
build.

Fixes #1021
Fixes #910
Fixes #173

### CODE REVIEW

File: go/tools/builders/protoc.go [hunk 1]
```diff
@@ -27,21 +28,32 @@ import (
...
 	plugin := flags.String("plugin", "", "The go plugin to use.")
 	importpath := flags.String("importpath", "", "The importpath for the generated sources.")
+	flags.Var(&options, "option", "The plugin options.")
+	flags.Var(&descriptors, "descriptor_set", "The descriptor set to read.")
 	flags.Var(&expected, "expected", "The expected output files.")
+	flags.Var(&imports, "import", "Map a proto file to an import path.")
 	if err := flags.Parse(args); err != nil {
 		return err
 	}
+	plugin_base := filepath.Base(*plugin)
```
Comment (jayconrod) [inline go/tools/builders/protoc.go]: Nit: `pluginBase` and `pluginName`

File: go/tools/builders/protoc.go [hunk 2]
```diff
@@ -57,22 +69,41 @@ func run(args []string) error {
 		}
 	}
 	if len(notFound) > 0 {
+		missing := []string{}
```
Comment (jayconrod) [inline go/tools/builders/protoc.go]: It doesn't seem like anything appends to this.

File: proto/compiler.bzl [hunk 3]
```diff
@@ -22,37 +22,32 @@ load("@io_bazel_rules_go//go/private:providers.bzl",
...
     go_srcs.append(out)
     if outpath == None:
         outpath = out.dirname[:-len(importpath)]
-  plugin_base_name = compiler.plugin.basename
-  if plugin_base_name.startswith(_protoc_prefix):
-    plugin_base_name = plugin_base_name[len(_protoc_prefix):]
   args = ctx.actions.args()
-  args.add(["-protoc", compiler.protoc.path])
   args.add([
+      "-protoc", compiler.protoc,
```
Comment (jayconrod) [inline proto/compiler.bzl]: Very small nit: `--protoc` for consistency with other options.

File: proto/def.bzl [hunk 4]
```diff
@@ -18,12 +19,31 @@ load("@io_bazel_rules_go//proto:compiler.bzl",
     "GoProtoCompiler",
 )
 
+GoProtoImports = provider()
+
+def get_imports(attr):
+    imports = []
```
Comment (jayconrod) [inline proto/def.bzl]: Style nit: 2-space indent for functions and if-statement.

File: go/tools/builders/protoc.go (hunk 2 above)
Comment (ianthehat) [reply go/tools/builders/protoc.go]: Was missing a commit that I merged to the wrong branch that improved error checking
when I was merging it though I decided to re-write the whole loop to be more thorough and easier to understand (I hope)

File: go/tools/builders/protoc.go (hunk 1 above)
Comment (ianthehat) [reply go/tools/builders/protoc.go]: That's what happens when you try to write skylark and go at the same time...

File: go/tools/builders/protoc.go [hunk 5]
```diff
@@ -26,6 +28,16 @@ import (
 	"strings"
 )
 
+type FileInfo struct {
```
Comment (jayconrod) [inline go/tools/builders/protoc.go]: I think it's a little confusing this has the same name as `os.FileInfo`. It doesn't need to be public though, right? Maybe `genFileInfo` would be a better name.

Also, consider making the fields non-public.

File: go/tools/builders/protoc.go [hunk 6]
```diff
@@ -62,47 +74,77 @@ func run(args []string) error {
...
-						}
-						if err := ioutil.WriteFile(matches[0], data, 0644); err != nil {
-							return err
-						}
-					}
-				}
-			}
+	// Walk the generated files
+	filepath.Walk(".", func(path string, f os.FileInfo, err error) error {
+		if !strings.HasSuffix(path, ".pb.go") {
```
Comment (jayconrod) [inline go/tools/builders/protoc.go]: Can't the suffix be something other than .pb.go? I thought the grpc gateway plugin generated something else.

File: go/tools/builders/protoc.go (hunk 5 above)
Comment (ianthehat) [reply go/tools/builders/protoc.go]: Meh, this entire directory is "private", it's all built directly to binaries and not libraries, and it's all in package main, so it's not like it can be imported.

File: go/tools/builders/protoc.go (hunk 6 above)
Comment (ianthehat) [reply go/tools/builders/protoc.go]: I have never run or seen the output of grpc-gateway, you may be right, who knows.
We can add an extra command line arg that passes in the expected extension from the compiler rule when we reach that bridge.

Comment (pcj) [reply go/tools/builders/protoc.go]: Drive-by comment...  Yes it can be `.pb.gw.go`.  I'm not sure there is an overall generalization.

https://github.com/pubref/rules_protobuf/blob/master/grpc_gateway/BUILD#L8

Comment (ianthehat) [reply go/tools/builders/protoc.go]: Okay, thanks!
I guess the real question is, do we even need to do this filtering, in theory there should not be any spare random files loafing around in this directory anyway... or maybe just .go is enough.
