### PR TITLE
Cope with cgo=True when there is no cgo

### LINKED ISSUE #678: Gazelle: incorrect definition for platform-dependent go/cgo package
`github.com/appc/spec/pkg/device` (https://github.com/appc/spec/tree/master/pkg/device) is an interesting corner case of a package that's purely go on Linux, and purely cgo on other Posix platforms.

Gazelle generates the following code for it:

```
load("@io_bazel_rules_go//go:def.bzl", "cgo_library", "go_library")

cgo_library(
    name = "cgo_default_library",
    srcs = select({
        "@io_bazel_rules_go//go/platform:darwin_amd64": ["device_posix.go"],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:private"],
)

go_library(
    name = "go_default_library",
    srcs = select({
        "@io_bazel_rules_go//go/platform:linux_amd64": ["device_linux.go"],
        "//conditions:default": [],
    }),
    library = ":cgo_default_library",
    visibility = ["//visibility:public"],
)
```

The problems are:
- on both Linux and Darwin, exactly one of the `srcs` will be empty, leading to a failure to build the corresponding target
- on Darwin, the final library should just be the cgo library

It's not clear to me what code *should* be generated instead.
I'm currently working around the problem by adding platform-agnostic dummy go and cgo files, but that's quite ugly :)

### PR DESCRIPTION
**Pull request by ianthehat**
This happens when a go library has cgo files that are only present in some
configurations.

Fixes #678

### CODE REVIEW

File: go/tools/builders/cgo.go [hunk 1]
```diff
@@ -144,6 +146,16 @@ func run(args []string) error {
 		}
 	}
 
+	if len(cgoSrcs) == 0 {
+		// If there were no cgo sources present, generate a minimal cgo input
+		// This is so we can still run the cgo tool to build all the other outputs
+		nullCgo := filepath.Join(objdir, "_cgo_empty.go")
+		cgoSrcs = append(cgoSrcs, nullCgo)
+		if err := ioutil.WriteFile(nullCgo, []byte("package "+pkg+"\n/* const int ___no_cgo_present; */\nimport \"C\"\n"), 0644); err != nil {
```
Comment (jayconrod) [inline go/tools/builders/cgo.go]: Will this cause a link error if there is more than one package like this? I think it will work, but it might be better to leave out the comment and just `import "C"`.

**Comment by ixdy** [comment]
This doesn't seem to work with one of our rules.

Using `rules_go` and `gazelle` at 473417ec, with the following BUILD snippet (`kubernetes/vendor/github.com/google/certificate-transparency/go/x509/BUILD`):
```python
go_library(
    name = "go_default_library",
    srcs = [
        "cert_pool.go",
        "pem_decrypt.go",
        "pkcs1.go",
        "pkcs8.go",
        "root.go",
        "sec1.go",
        "verify.go",
        "x509.go",
    ] + select({
        "@io_bazel_rules_go//go/platform:linux_amd64": ["root_unix.go"],
        "@io_bazel_rules_go//go/platform:windows_amd64": ["root_windows.go"],
        "//conditions:default": [],
    }),
    library = ":cgo_default_library",
    tags = ["automanaged"],
    deps = [
        "//vendor/github.com/google/certificate-transparency/go/asn1:go_default_library",
        "//vendor/github.com/google/certificate-transparency/go/x509/pkix:go_default_library",
    ],
)

cgo_library(
    name = "cgo_default_library",
    srcs = select({
        "@io_bazel_rules_go//go/platform:darwin_amd64": ["root_darwin.go"],
        "//conditions:default": [],
    }),
    clinkopts = select({
        "@io_bazel_rules_go//go/platform:darwin_amd64": ["-framework CoreFoundation -framework Security"],
        "//conditions:default": [],
    }),
    copts = select({
        "@io_bazel_rules_go//go/platform:darwin_amd64": ["-mmacosx-version-min=10.6 -D__MAC_OS_X_VERSION_MAX_ALLOWED=1060"],
        "//conditions:default": [],
    }),
)
```

I get the following build failure:
```
ERROR: [HOME]/code/kubernetes/src/k8s.io/kubernetes/vendor/github.com/google/certificate-transparency/go/x509/BUILD:51:1: Couldn't build file vendor/github.com/google/certificate-transparency/go/x509/cgo_default_library.cgo.dir/_cgo_gotypes.go: CGoCodeGen //vendor/github.com/google/certificate-transparency/go/x509:cgo_default_library.cgo_codegen failed (Exit 1): cgo failed: error executing command bazel-out/host/bin/external/io_bazel_rules_go/go/tools/builders/cgo external/go1_8_3_linux_amd64/bin/go -cc /usr/bin/gcc -objdir ... (remaining 5 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
[HOME]/.cache/bazel/_bazel_jgrafton/75e5737b0f848bf1b7c3ab3303c8bf72/bazel-sandbox/5090494783276797514/execroot/__main__/bazel-out/local-fastbuild/bin/vendor/github.com/google/certificate-transparency/go/x509/cgo_default_library.cgo.dir/_cgo_empty.go:4:1: expected 'IDENT', found 'import'
2017/08/03 00:04:45 error running cgo: exit status 1
```

**Comment by ixdy** [comment]
(This is on linux/amd64 with bazel 0.5.3)

**Comment by ixdy** [comment]
ah, I think I probably need #684 and #685 before this is expected to work?

**Comment by jayconrod** [comment]
This looks like a new bug. A placeholder cgo file is empty. I'll work on a fix.

**Comment by jayconrod** [comment]
I take it back. The problem is just that `cgo_library` will fix this. #684, #685, and another upcoming change in Gazelle will fix this.

Once those changes are in, you'll need to run `gazelle fix` to squash the `cgo_library` and `go_library` rules together. It's an invasive change that we won't attempt automatically.

Our error message here is not very good. I'll change that and make cgo package name checking stricter.

**Comment by ixdy** [comment]
I built a custom `gazelle` last night with #684 and #685 patched in, ran it on the Kubernetes repo, and everything built + passed unit tests. We don't need `gazelle fix` (yet) because we don't have any of the "bad" `cgo_library` rules in our `BUILD` files.
