### PR TITLE
tools/upgradedep: add support for Label based repositories.bzl

### LINKED ISSUE #3050: Dependency upgrader fails to run due to change to Label() dependencies
### What version of rules_go are you using?

N/A trying to release rules_go.

### What version of gazelle are you using?

v0.22.3

### What version of Bazel are you using?

4.2.2

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Debian 10

### Any other potentially useful information about your toolchain?

Just pulled master of rules_go

### What did you do?

Running `bazel run //go/tools/releaser -- upgrade-dep all` results in a `upgrading com_github_golang_protobuf: not all patches are string literals` error, due to the Label change in repositories.bzl.

Working on a fix now so I can release v0.30.0 (#3049). Just wanted to make the issue to track.

### PR DESCRIPTION
**Pull request by JamyDev**
**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**

upgradedep.go was not working due to the change to Label() based patches in #3035. Modified the parser to support both string and Label() patches.

Added tests to ensure all cases are covered for the additional code.

**Which issues(s) does this PR fix?**

Fixes #3050

**Other notes for review**

### CODE REVIEW

File: go/tools/releaser/upgradedep_test.go [hunk 1]
```diff
@@ -0,0 +1,123 @@
...
+	"io/ioutil"
+	"testing"
+
+	bzl "github.com/bazelbuild/buildtools/build"
+	"github.com/bazelbuild/rules_go/go/tools/bazel"
+)
+
+const (
+	reposFile = "go/tools/releaser/testdata/repositories.bzl"
+	funcName  = "go_rules_dependencies"
```
Comment (linzhp) [inline go/tools/releaser/upgradedep_test.go:14]:
```suggestion
	_reposFile = "go/tools/releaser/testdata/repositories.bzl"
	_funcName  = "go_rules_dependencies"
```

[Prefix Unexported Globals with _](https://github.com/uber-go/guide/blob/master/style.md#prefix-unexported-globals-with-_)

File: go/tools/releaser/upgradedep_test.go [hunk 2]
```diff
@@ -0,0 +1,123 @@
...
+)
+
+func TestPatchItemParser(t *testing.T) {
```
Comment (linzhp) [inline go/tools/releaser/upgradedep_test.go:17]: This test adds a lot of complexity just to cover whether whether a patch expression is parsed correctly. Can we avoid all the file loading and rule parsing in the test by doing something like:

```go
patchExpr, err := bzl.Parse("repos.bzl", 
[]byte(`# releaser:patch-cmd gazelle -repo_root . -go_prefix golang.org/x/tools -go_naming_convention import_alias
 Label("//third_party:org_golang_x_tools-gazelle.patch")`))
if err != nil {
   t.Fatalf(...)
}
patchLabelStr, comment, err := parsePatchesItem(patchExpr)
if patchLabelStr != "//third_party:org_golang_x_tools-gazelle.patch" {
  t.Fatalf(...)
}
```

**Comment by linzhp** [comment]
The other way to test this PR is to extract the logic that reads `repositories.bzl` to a separate function, and read the real `repositories.bzl` to test that function. That way, future incompatible changes to `repositories.bzl` will fail that test.

File: go/tools/releaser/upgradedep_test.go (hunk 2 above)
Comment (JamyDev) [reply go/tools/releaser/upgradedep_test.go:17]: Oh that makes sense. Didn't immediately think that we don't really need all the wrapping around the test. I'll put something together in the AM.

**Comment by JamyDev** [comment]
I think reading the entire repositories file and doing a dry run of the upgrader would be a good integration test case, but that would bloat this PR, so that's a separate piece of work.

File: go/tools/releaser/upgradedep.go [hunk 3]
```diff
@@ -488,6 +489,45 @@ func upgradeDepDecl(ctx context.Context, gh *githubClient, workDir, name string,
...
+	patchLabelCall, ok := patchLabelExpr.(*bzl.CallExpr)
+
+	if ok {
+		// Verify the identifier, should be Label
+		ident, ok := patchLabelCall.X.(*bzl.Ident)
+		if !ok {
+			return "", nil, fmt.Errorf("invalid identifier while parsing patch label")
+		}
+		if ident.Name != "Label" {
+			return "", nil, fmt.Errorf("invalid patch function: %s", ident.Name)
```
Comment (blico) [inline go/tools/releaser/upgradedep.go:503]: NIT: `%q` is generally preferred over `%s` for error strings

File: go/tools/releaser/upgradedep.go [hunk 4]
```diff
@@ -433,19 +433,20 @@ func upgradeDepDecl(ctx context.Context, gh *githubClient, workDir, name string,
...
-				return fmt.Errorf("not all patches are string literals")
+			patchLabelValue, comments, err := parsePatchesItem(patchLabelExpr)
+			if err != nil {
+				return err
 			}
-			if !strings.HasPrefix(patchLabel.Value, "@io_bazel_rules_go//third_party:") {
-				return fmt.Errorf("patch does not start with '@io_bazel_rules_go//third_party:': %s", patchLabel)
+
+			if !strings.HasPrefix(patchLabelValue, "//third_party:") {
+				return fmt.Errorf("patch does not start with '//third_party:': %s", patchLabelValue)
```
Comment (blico) [inline go/tools/releaser/upgradedep.go:442]: NIT: `%q` instead of `%s`

**Comment by blico** [comment]
Looks good besides some mostly stylistic comments.

File: go/tools/releaser/upgradedep_test.go [hunk 5]
```diff
@@ -0,0 +1,89 @@
...
+
+	for _, tt := range tests {
+		t.Run(fmt.Sprintf("%v", tt.expression), func(t *testing.T) {
+			patchExpr, err := bzl.Parse("repos.bzl", tt.expression)
+			if err != nil {
+				t.Fatalf(err.Error())
+			}
+
+			patchLabelStr, _, err := parsePatchesItem(patchExpr.Stmt[0])
+			if err != nil && err.Error() != tt.error {
```
Comment (linzhp) [inline go/tools/releaser/upgradedep_test.go:72]: I prefer to break this into two test tables: `TestPatchItemParser_Success` and `TestPatchItemParser_Error`. That way we can keep the assertions exactly the same for each test table and avoid some branching logic in the test body. In general, we should avoid putting logic in the tests [1][2], because we have tests to cover production logic, but we don't have tests to cover test logic.

[1] https://learning.oreilly.com/library/view/software-engineering-at/9781492082781/ch12.html#donapostrophet_put_logic_in_tests
[2] https://learning.oreilly.com/library/view/software-engineering-at/9781492082781/ch12.html#tests_and_code_sharing_dampcomma_not_dr

Comment (JamyDev) [reply go/tools/releaser/upgradedep_test.go]: Totally fair, was mapping my original case (repos.bzl test file) into a single test, but obviously the landscape changed a little.
