### PR TITLE
Fix invocation of assembler for go1.22

### LINKED ISSUE #3755: Go1.22 (devel) packages with assembly source files do not link due to ABI mismatch
### What version of rules_go are you using?

Attempted with both:

(master, f2d409bc52d4945f283e89f8b501cbab65c83fbb)
(0.42.0, c2406b27f77e186d0fb3548d8526e6c14a3236d4)

### What version of gazelle are you using?

```
http_archive(
    name = "bazel_gazelle",
    sha256 = "d3fa66a39028e97d76f9e2db8f1b0c11c099e8e01bf363a923074784e451f809",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.33.0/bazel-gazelle-v0.33.0.tar.gz",
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.33.0/bazel-gazelle-v0.33.0.tar.gz",
    ],
)
```
### What version of Bazel are you using?

```
% bazel version
Build label: 6.4.0-homebrew
Build target: bazel-out/darwin_arm64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jan 1 00:00:00 1980 (315532800)
Build timestamp: 315532800
Build timestamp as int: 315532800
```

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

```
go env
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/jeremyquirke/Library/Caches/go-build'
GOENV='/Users/jeremyquirke/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/jeremyquirke/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/jeremyquirke/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/Users/jeremyquirke/go/src/github.com/jquirke/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/Users/jeremyquirke/go/src/github.com/jquirke/go/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='devel go1.22-b9a08f159d Thu Nov 16 22:15:45 2023 +0000'
GCCGO='gccgo'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Users/jeremyquirke/go/src/github.com/jquirke/rules_go/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/sp/4_zrh6x535z84nc2_b1s0cvh0000gn/T/go-build3565868472=/tmp/go-build -gno-record-gcc-switches -fno-common'
go env
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/jeremyquirke/Library/Caches/go-build'
GOENV='/Users/jeremyquirke/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/jeremyquirke/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/jeremyquirke/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/Users/jeremyquirke/go/src/github.com/jquirke/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/Users/jeremyquirke/go/src/github.com/jquirke/go/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='devel go1.22-b9a08f159d Thu Nov 16 22:15:45 2023 +0000'
GCCGO='gccgo'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Users/jeremyquirke/go/src/github.com/jquirke/rules_go/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/sp/4_zrh6x535z84nc2_b1s0cvh0000gn/T/go-build3565868472=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### Any other potentially useful information about your toolchain?

Working with the development branch of Go

```
 go version
go version devel go1.22-b9a08f159d Thu Nov 16 22:15:45 2023 +0000 darwin/arm64
```

### What did you do?

Build this simple program using Bazel+Gazelle using 

```
go version devel go1.22-b9a08f159d Thu Nov 16 22:15:45 2023 +0000 darwin/arm64
```

```
package main

import (
	"bytes"
	"fmt"
	"io"
	"io/ioutil"

	"github.com/klauspost/compress/s2"
)

func main() {

	buf := &bytes.Buffer{}
	enc := s2.NewWriter(buf)
	_, err := io.Copy(enc, bytes.NewReader([]byte("Hello world Hello world")))
	if err != nil {
		enc.Close()
		return
	}
	enc.Close()

	dec := s2.NewReader(buf)
	str, err := ioutil.ReadAll(dec)

	fmt.Printf("%v %v\n", string(str), err)
}
```

```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "91585017debb61982f7054c9688857a2ad1fd823fc3f9cb05048b0025c47d023",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.42.0/rules_go-v0.42.0.zip",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.42.0/rules_go-v0.42.0.zip",
    ],
)

http_archive(
    name = "bazel_gazelle",
    sha256 = "d3fa66a39028e97d76f9e2db8f1b0c11c099e8e01bf363a923074784e451f809",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.33.0/bazel-gazelle-v0.33.0.tar.gz",
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.33.0/bazel-gazelle-v0.33.0.tar.gz",
    ],
)

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_local_sdk", "go_rules_dependencies")
load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies", "go_repository")

go_repository(
    name = "com_github_klauspost_compress",
    importpath = "github.com/klauspost/compress",
    sum = "h1:RlWWUY/Dr4fL8qk9YG7DTZ7PDgME2V4csBXA8L/ixi4=",
    version = "v1.17.2",
)

go_local_sdk(
    name = "go_sdk",
    path = "/Users/jeremyquirke/go/src/github.com/jquirke/go"
)

go_rules_dependencies()

go_register_toolchains()

gazelle_dependencies()
```
### What did you expect to see?

Successful executable built.

### What did you see instead?

```
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
github.com/klauspost/compress/s2.Decode: relocation target github.com/klauspost/compress/s2.s2Decode not defined for ABIInternal (but is defined for ABI0)
link: error running subcommand external/go_sdk/pkg/tool/darwin_arm64/link: exit status 2
```

### Analysis

In go1.19 through go1.22-devel (as of https://github.com/golang/go/commit/6382893890b82bbc0439eade5b132d9d1b3fb3a7) a series of changes are made to the way assembly source file symabis are produced. 

https://go-review.googlesource.com/c/go/+/523337

Namely, that the packagename now *must* passed to the assembler via the -p flag, even when generating only the symabis. The go build system does this, but Bazel Go rules do not, and this finally breaks in go1.22 due to the final removal of the fallback compatibliity code.

Now, without specifying -p to the assembler when generating symabis, the output symabis file will contain something like:

```
def <unlinkable>.s2Decode ABI0
```

instead of

```
def github.com/klauspost/compress/s2.s2Decode ABI0
```

The result is that the compiler will default to using ABIInternal instead of ABI0 if it cannot resolve the imported symbols ABI in the symabis file, and declare their symbols as ABIInternal in the assembled object files NonPkgDef.

This will inevitably cause a link failure as the consuming object files declare their expecatation of ABI0 in their NonPkgRefs.

### PR DESCRIPTION
**Pull request by jquirke**
**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**

In go1.19 through go1.22-devel (as of https://github.com/golang/go/commit/6382893890b82bbc0439eade5b132d9d1b3fb3a7) a series of changes were made to the way assembly files' symabis are produced.

https://go-review.googlesource.com/c/go/+/523337

Most significantly, the packagename now *must* be passed to the assembler via the -p flag, even when generating only the symabis. The go build system does this, but Bazel Go rules have not, and this finally breaks in go1.22-devel as the compatibility code is removed.

Now, without specifying -p to the assembler when generating symabis, the output symabis file will contain something like:

```
def <unlinkable>.s2Decode ABI0
```

instead of

```
def github.com/klauspost/compress/s2.s2Decode ABI0
```

The result is that the compiler will default to using ABIInternal instead of ABI0 if it cannot resolve the imported symbol's ABI in symabis, and default the symbol as ABIInternal in the assembled object files NonPkgDefs.

This will inevitably cause a link failure as the consuming object files declare their expecatation of ABI0 in their NonPkgRefs.

```
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
github.com/klauspost/compress/s2.Decode: relocation target github.com/klauspost/compress/s2.s2Decode not defined for ABIInternal (but is defined for ABI0)
link: error running subcommand external/go_sdk/pkg/tool/darwin_arm64/link: exit status 2
```

**Which issues(s) does this PR fix?**

Fixes #3755,  #3849

**Other notes for review**

### CODE REVIEW

File: go/tools/builders/asm.go [hunk 1]
```diff
@@ -94,6 +94,12 @@ func buildSymabisFile(goenv *env, sFiles, hFiles []fileInfo, asmhdr string) (str
 			seenHdrDirs[hdrDir] = true
 		}
 	}
+	// The package path has to be specified as of Go 1.22 or the resulting
+	// object will be unlinkable, but the -p flag is only required in
+	// preparing symabis since Go1.22
+	if packagePath != "" && isGo119OrHigher() {
```
Comment (sywhang) [inline go/tools/builders/asm.go:100]:
```suggestion
	if packagePath != "" && isGo121OrHigher() {
```
I think you meant to do this?

Comment (jquirke) [reply go/tools/builders/asm.go]: Ah yeah, thanks

**Review by sywhang — APPROVED** [review]
LGTM. @linzhp could you please take a look?

File: go/tools/builders/asm.go [hunk 2]
```diff
@@ -94,6 +94,12 @@ func buildSymabisFile(goenv *env, sFiles, hFiles []fileInfo, asmhdr string) (str
 			seenHdrDirs[hdrDir] = true
 		}
 	}
+	// The package path has to be specified as of Go 1.22 or the resulting
+	// object will be unlinkable, but the -p flag is only required in
+	// preparing symabis since Go1.22
+	if packagePath != "" && isGoMinorVersionEqualHigher(22) {
```
Comment (fmeum) [inline go/tools/builders/asm.go:100]: Since when has `go build` been passing the package path? I would slightly prefer mimicking its behavior, even if that means changing command lines with Go 1.21 and earlier. With our current CI setup, we otherwise wouldn't have coverage for this code path as we are still on 1.21.

Comment (jquirke) [reply go/tools/builders/asm.go:100]: Since Go1.19: https://go-review.googlesource.com/c/go/+/404298

However, not passing package path finally broke in August 2023 on go1.22-devel: https://go-review.googlesource.com/c/go/+/523336/7/src/cmd/asm/internal/asm/parse.go

Comment (jquirke) [reply go/tools/builders/asm.go:100]: But fair, I'll change the logic so that both branches are for Go1.19?

**Review by fmeum — APPROVED** [review]
Has this been tested at Uber?

Cc @tyler-french

**Comment by jquirke** [comment]
> Has this been tested at Uber?
> 
> Cc @tyler-french 

I'm testing the PR rebased on v0.42.0 in Uber internal diff D11928203

**Comment by sluongng** [comment]
I tested this on BuildBuddy repo + Go SDK 1.22.0 and it worked. Without this PR it would fail the same way stated in the PR summary.

Thanks for submitting this. 🙏
