### PR TITLE
Fixes and tests for reproducibility

### LINKED ISSUE #1518: Absolute paths from stdlib are embedded in the binary
With rules_go 0.12 and go 1.10.2, I see that my stripped binaries are not reproducible on clean builds.

On using [diffoscope](https://diffoscope.org/), I was able to see that there were absolute paths to stdlib files embedded in the binary and that was the only difference. Since these paths are sandboxed paths, they will be different on each run.

I can see many closed github issues about reproducibility and ones that deal specifically with this, but my observation on the latest release is different.

Willing to help in any way I can.

### LINKED ISSUE #1547: Builds not reproducible with cgo (?)
Possibly related to #1531 , and might be the issue being fixed in #1536

Builds (that involve cgo?) produce different binaries from run to run.  For example https://github.com/kopeio/etcd-manager

```
bazel build //cmd/etcd-manager
md5sum bazel-bin/cmd/etcd-manager/linux_amd64_stripped/etcd-manager
# b9ccdf4bcc329e27b04260dc26dd3580  bazel-bin/cmd/etcd-manager/linux_amd64_stripped/etcd-manager
bazel clean
bazel build //cmd/etcd-manager
md5sum bazel-bin/cmd/etcd-manager/linux_amd64_stripped/etcd-manager
9c77176ee931b35dcdbdbd0287d24418  bazel-bin/cmd/etcd-manager/linux_amd64_stripped/etcd-manager
```

I believe this is because the sandbox path is included in the binary:

```
> strings bazel-bin/cmd/etcd-manager/linux_amd64_stripped/etcd-manager | grep main...bazel-out
/home/justinsb/.cache/bazel/_bazel_justinsb/4a499e13846793b0120bbd2f7639609a/sandbox/processwrapper-sandbox/380/execroot/__main__/bazel-out/k8-fastbuild/bin/external/io_bazel_rules_go/linux_amd64_stripped/stdlib~/src/runtime/cgo
/home/justinsb/.cache/bazel/_bazel_justinsb/4a499e13846793b0120bbd2f7639609a/sandbox/processwrapper-sandbox/380/execroot/__main__/bazel-out/k8-fastbuild/bin/external/io_bazel_rules_go/linux_amd64_stripped/stdlib~/src/os/user
/home/justinsb/.cache/bazel/_bazel_justinsb/4a499e13846793b0120bbd2f7639609a/sandbox/processwrapper-sandbox/380/execroot/__main__/bazel-out/k8-fastbuild/bin/external/io_bazel_rules_go/linux_amd64_stripped/stdlib~/src/os/user
/home/justinsb/.cache/bazel/_bazel_justinsb/4a499e13846793b0120bbd2f7639609a/sandbox/processwrapper-sandbox/380/execroot/__main__/bazel-out/k8-fastbuild/bin/external/io_bazel_rules_go/linux_amd64_stripped/stdlib~/src/runtime/cgo
```

(And 380 changes in between invocations)

In bazel-bin:

```
> rgrep __main__ .
./cmd/etcd-manager/linux_amd64_stripped/etcd-manager.runfiles_manifest:__main__/cmd/etcd-manager/linux_amd64_stripped/etcd-manager /home/justinsb/.cache/bazel/_bazel_justinsb/4a499e13846793b0120bbd2f7639609a/execroot/__main__/bazel-out/k8-fastbuild/bin/cmd/etcd-manager/linux_amd64_stripped/etcd-manager
./cmd/etcd-manager/linux_amd64_stripped/etcd-manager.runfiles/MANIFEST:__main__/cmd/etcd-manager/linux_amd64_stripped/etcd-manager /home/justinsb/.cache/bazel/_bazel_justinsb/4a499e13846793b0120bbd2f7639609a/execroot/__main__/bazel-out/k8-fastbuild/bin/cmd/etcd-manager/linux_amd64_stripped/etcd-manager
Binary file ./cmd/etcd-manager/linux_amd64_stripped/etcd-manager matches
Binary file ./external/io_bazel_rules_go/linux_amd64_stripped/stdlib~/pkg/linux_amd64/runtime/cgo.a matches
Binary file ./external/io_bazel_rules_go/linux_amd64_stripped/stdlib~/pkg/linux_amd64/plugin.a matches
Binary file ./external/io_bazel_rules_go/linux_amd64_stripped/stdlib~/pkg/linux_amd64/os/user.a matches
```

So it's coming from those .a files, which I think are the ones that aren't cached in #1531.

### PR DESCRIPTION
**Pull request by siddharthab**
Includes a reproducibility test in travis, that will test if stdlib and binaries with cgo are reproducible across multiple builds by the same user. This still does not test if the binaries are reproducible across multiple users or machines. I am relying on tests/legacy/reproducible_binary to check that.

There are two fixes included here:
1. Supplying -fdebug-prefix-map to C compiler invocations for cgo.
2. Stripping temp dir path from generated src files (*.cgo2.c).

Resolves #1518.
Resolves #1547.

### CODE REVIEW

**Comment by siddharthab** [comment]
You can see that the test fails in the first travis run because the PR did not have the commit for the fixes for that run. The second travis run which includes the commit for the fixes passes.

Please ignore the main `bazel test` run failure in the first travis run. I accidentally deleted a line in the travis config which led to command line parsing errors.

File: tests/core/reproducibility/test.sh [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+    "--output_base=${output_base}"  # Use a disposable output_base.
+    )
+    build_opts=()
+
+    if [[ $(uname -s) == "Linux" ]]; then
+      # Use shared memory sandbox for faster runs.
+      build_opts+=("--experimental_sandbox_base=/dev/shm")
+    fi
+
+    bazel "${bazel_opts[@]}" build "${build_opts[@]+"${build_opts[@]}"}" \
```
Comment (jayconrod) [inline tests/core/reproducibility/test.sh]: I'm not familiar with the syntax for expanding `build_opts` here. Can it just be `"${build_opts[@]}"`?

File: tests/core/reproducibility/test.sh [hunk 2]
```diff
@@ -0,0 +1,49 @@
+#!/bin/bash
+set -eu -o pipefail
+
+function run_bazel() {
+    local output_base
```
Comment (jayconrod) [inline tests/core/reproducibility/test.sh]: Assigning `"$1"` to another local here would improve readability.

File: tests/core/reproducibility/test.sh [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+    )
+    build_opts=()
+
+    if [[ $(uname -s) == "Linux" ]]; then
+      # Use shared memory sandbox for faster runs.
+      build_opts+=("--experimental_sandbox_base=/dev/shm")
+    fi
+
+    bazel "${bazel_opts[@]}" build "${build_opts[@]+"${build_opts[@]}"}" \
+      //tests/core/go_binary:all \
```
Comment (jayconrod) [inline tests/core/reproducibility/test.sh]: It would be better to test against targets in this directory instead of elsewhere. `//tests/core/go_binary:all` may pick up some unexpected things, depending on what we put in there in the future. It's better for this test to be isolated.

Comment (siddharthab) [reply tests/core/reproducibility/test.sh]: Alright. I will create some binary with cgo here.

File: tests/core/reproducibility/test.sh (hunk 2 above)
Comment (siddharthab) [reply tests/core/reproducibility/test.sh]: Done.

File: tests/core/reproducibility/test.sh (hunk 1 above)
Comment (siddharthab) [reply tests/core/reproducibility/test.sh]: Now removed, so no longer applicable. But the main reason was that empty arrays are considered unset in most bash versions. This will trigger the trap in `set -u` and the script fails. The syntax I had is the alternative value mechanism.
http://wiki.bash-hackers.org/syntax/pe#use_an_alternate_value

File: tests/core/reproducibility/test.sh [hunk 4]
```diff
@@ -0,0 +1,49 @@
...
+    local build_opts
+
+    output_base=$(mktemp -d)
+    bazel_opts=(
+    "--bazelrc=/dev/null"  # Disable any user specified remote/disk caching.
+    "--output_base=${output_base}"  # Use a disposable output_base.
+    )
+    build_opts=()
+
+    if [[ $(uname -s) == "Linux" ]]; then
```
[the remark this answers is not in the document]
Comment (siddharthab) [reply tests/core/reproducibility/test.sh]: Removed.

File: .travis.yml [hunk 5]
```diff
@@ -58,6 +58,8 @@ script:
       --local_resources=400,1,1.0 \
       --test_tag_filters=-dev \
       //...
+  - tests/core/reproducibility/test.sh
```
[the remark this answers is not in the document]
Comment (siddharthab) [reply .travis.yml]: Looking into it.

[the remark this answers is not in the document]
Comment (siddharthab) [reply .travis.yml]: Done.

File: tests/core/reproducibility/test.sh (hunk 3 above)
Comment (siddharthab) [reply tests/core/reproducibility/test.sh]: Done.

**Comment by siddharthab** [comment]
I have addressed all current comments. I also reorganized the commits so that I could run the new tests without the fixes and see how they fail.

**Comment by siddharthab** [comment]
Two more commits to make the tests pass and some hygiene.

**Comment by siddharthab** [comment]
Reorganize commits again and use bundled md5sum because macOS travis image does not have md5sum.

**Comment by siddharthab** [comment]
Travis test failures are unrelated.
