### PR TITLE
gazelle: don't rewrite files with gazelle:ignore

### LINKED ISSUE #266: gazelle can modify a "# gazelle:ignore" BUILD file
Running gazelle to regenerate a BUILD file containing `# gazelle:ignore` can modify the existing file. It appears that the changes are only reordering/cleanup of the existing rules, with no structural changes. However, the docs say "# gazelle:ignore in a BUILD file will instruct gazelle to leave the file alone.", which isn't true.

One possible fix would be to update the documentation for accuracy.

Another possible fix would be to avoid writing out anything when the ignore directive appears. 

I can see arguments for both the cleanup mode (the existing behavior) and the strict non-intervention mode (what the documentation says). I think either of my proposals would address the problem.

The ideal solution might be to use the strict mode by default, then also provide a `--cleanup` mode which executes the existing cleanup behavior.

### To reproduce
```
mkdir -p gazelle_test/code
cd gazelle_test/
echo "package main\nfunc main() {}" > code/main.go
print "# gazelle:ignore\n\n\n# some comment" > BUILD.orig
print "# gazelle:ignore\n\n\n# some comment" > BUILD
gazelle --repo_root=. --go_prefix=code
diff code/BUILD.orig code/BUILD
```
produces:
```
3,4c3
< 
< # some comment
\ No newline at end of file
---
> # some comment
```
i.e. some whitespace was removed. Other changes are also possible, such as reordering of build rule attributes.

### Random implementation thought

One possible approach to implementing the strict mode might be to use something like this in gazelle's main.go where MergeWithExisting() is called.
https://github.com/bazelbuild/rules_go/blob/master/go/tools/gazelle/gazelle/main.go#L101
```
f, err := merger.MergeWithExisting(f, existingFilePath)
switch err.(type) {
    case nil:
        // write out the generated file as usual
    case GazelleIgnoreErr:  // "# gazelle:ignore" was seen
        // cancel further processing of this BUILD, but continue
        // the loop to process other BUILDs.
        continue  
    case error:
        return err // interrupt the loop and cancel program execution          
}
```

### PR DESCRIPTION
**Pull request by jayconrod**
Previously, Gazelle would avoid merging files with a "#
gazelle:ignore" comment, but it would still rewrite them. This could
result in small changes, e.g., whitespace.

Gazelle will no longer rewrite these files at all.

Fixes #266.

### CODE REVIEW

**Comment by jayconrod** [comment]
Travis builds are timing out due to an Amazon S3 outage. [Travis status](https://www.traviscistatus.com/incidents/hmwq9yy5dh9d)

I'll rerun the builds when it's back up.

**Comment by pmbethe09** [comment]
Not sure about this one. 
Does '# gazelle:ignore' mean "leave this file completely alone", or just "only run buildifier".

IMHO, all of your BUILD files should be formatted by buildifier, so in the case of gazelle:ignore, rather than doing nothing, you should return the on-disk AST and then write the file back out.

**Comment by jayconrod** [comment]
README.md says:

> `# gazelle:ignore` in a BUILD file will instruct gazelle to leave the file alone.

I agree that buildifier should be run in most cases, but I think users should have a way to opt out of it. If we want to preserve the old behavior, maybe we should rename the directive to "# gazelle:format-only"?

**Comment by pmbethe09** [comment]
Hmm, good point.

File: go/tools/gazelle/merger/merger_test.go [hunk 1]
```diff
@@ -115,9 +116,17 @@ func TestMergeWithExisting(t *testing.T) {
...
+		if _, ok := err.(GazelleIgnoreError); ok {
+			if !tc.ignore {
+				t.Fatalf("unexpected ignore: %v", err)
+			}
+			continue
+		} else if err != nil {
 			t.Fatal(err)
 		}
+		if tc.ignore {
+			t.Fatal("expected ignore")
```
Comment (pmbethe09) [inline go/tools/gazelle/merger/merger_test.go]: Error ?

Comment (jayconrod) [inline go/tools/gazelle/merger/merger_test.go]: Fixed. Will submit when Travis is back up.
