### PR TITLE
cgo packages with assembly: Support CGO_ENABLED=0

### LINKED ISSUE #3411: builds with cgo appear to miss .S assembly files
### What version of rules_go are you using?

0.35.0

### What version of gazelle are you using?

0.27.0

### What version of Bazel are you using?

Build label: 5.4.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

```
$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```

### What did you do?

I am attempting to [build Go program](https://github.com/tals/bazel-rulesgo-broken-asm-repro) using the popular [zstd package from DataDog](https://github.com/DataDog/zstd)
This library vendors zstd, which includes accelerated operations in the .S file.

This works well with the vanilla go toolchain, however building this via rules_go fails to pick up an .S file for amd64, causing it to fail during link time

```
$ git clone https://github.com/tals/bazel-rulesgo-broken-asm-repro
$ cd bazel-rulesgo-broken-asm-repro
$ go run main.go
Hello, World!

$ bazel run  //:hello-go

INFO: Analyzed target //:hello-go (26 packages loaded, 195 targets configured).
INFO: Found 1 target...
ERROR: /home/tal/.cache/bazel/_bazel_tal/d6d42962320318bd35977430f4d78b15/external/com_github_datadog_zstd/BUILD.bazel:3:11: GoCompilePkg external/com_github_datadog_zstd/zstd.a failed: (Exit 1): builder failed: error executing command bazel-out/k8-opt-exec-2B5CBBC6/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -src external/com_github_datadog_zstd/errors.go -src ... (remaining 211 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
/tmp/rules_go_work-585792782/cgo/github.com/DataDog/zstd/_x16.o:huf_decompress.c:function HUF_decompress4X1_usingDTable_internal_bmi2_asm: error: undefined reference to 'HUF_decompress4X1_usingDTable_internal_bmi2_asm_loop'
/tmp/rules_go_work-585792782/cgo/github.com/DataDog/zstd/_x16.o:huf_decompress.c:function HUF_decompress4X2_usingDTable_internal_bmi2_asm: error: undefined reference to 'HUF_decompress4X2_usingDTable_internal_bmi2_asm_loop'
collect2: error: ld returned 1 exit status
compilepkg: error running subcommand /usr/bin/gcc: exit status 1
Target //:hello-go failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 4.087s, Critical Path: 3.93s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

The Gazelle-generated project does include the .S file, however:
```
go_library(
    name = "zstd",
    srcs = [
        ...
        "huf_compress.c",
        "huf_decompress.c",
        "huf_decompress_amd64.S", # <---
```

### What did you expect to see?

Hello, World!

### What did you see instead?
```
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
/tmp/rules_go_work-585792782/cgo/github.com/DataDog/zstd/_x16.o:huf_decompress.c:function HUF_decompress4X1_usingDTable_internal_bmi2_asm: error: undefined reference to 'HUF_decompress4X1_usingDTable_internal_bmi2_asm_loop'
/tmp/rules_go_work-585792782/cgo/github.com/DataDog/zstd/_x16.o:huf_decompress.c:function HUF_decompress4X2_usingDTable_internal_bmi2_asm: error: undefined reference to 'HUF_decompress4X2_usingDTable_internal_bmi2_asm_loop'
collect2: error: ld returned 1 exit status
compilepkg: error running subcommand /usr/bin/gcc: exit status 1
Target //:hello-go failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 4.087s, Critical Path: 3.93s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

### PR DESCRIPTION
**Pull request by evanj**
**What type of PR is this?**

> Uncomment one line below and remove others.
>
Bug fix

**What does this PR do? Why is it needed?**

Go supports building cgo packages both with and without Cgo. It uses build constraints to exclude the appropriate files. When building a Cgo package with assembly files, we must exclude them. Previous to this change, rules_go would run the Go assembler on them. This meant that packages which had "conditional" imports of cgo libraries with assembly would fail when compiled with cgo disabled.

Add tests for these two cases:
* asm_conditional_cgo: A Go package that compiles both with and without Cgo.
* asm_dep_conditional_cgo: A Go package that conditionally imports a package with Cgo.

**Which issues(s) does this PR fix?**

Fixes #3411

**Other notes for review**

I tested this with the DataDog/zstd package. This now works both with and without cgo/cross compilation: https://github.com/evanj/ddzstdbazel

### CODE REVIEW

File: tests/core/cgo/asm_dep_conditional_cgo/asm_dep_conditional_cgo.go [hunk 1]
```diff
@@ -0,0 +1,14 @@
+package main
```
Comment (fmeum) [inline tests/core/cgo/asm_dep_conditional_cgo/asm_dep_conditional_cgo.go:1]: Is this file used anywhere?

File: tests/core/cgo/asm_conditional_cgo/asm_cgo.go [hunk 2]
```diff
@@ -0,0 +1,16 @@
+//go:build amd64 || arm64
```
Comment (fmeum) [inline tests/core/cgo/asm_conditional_cgo/asm_cgo.go:1]: Slightly surprised that this works without the `cgo` constraint here. In the non-cgo case, isn't `callASM` defined twice?

File: tests/core/cgo/asm_conditional_cgo/asm_conditional_cgo.go [hunk 3]
```diff
@@ -0,0 +1,14 @@
+package main
```
Comment (fmeum) [inline tests/core/cgo/asm_conditional_cgo/asm_conditional_cgo.go:1]: This also seems to be unused.

File: go/tools/builders/compilepkg.go [hunk 4]
```diff
@@ -273,7 +273,9 @@ func compileArchive(
 		hSrcs[i] = src.filename
 	}
 	haveCgo := len(cgoSrcs)+len(cSrcs)+len(cxxSrcs)+len(objcSrcs)+len(objcxxSrcs) > 0
-	packageUsesCgo := cgoEnabled && haveCgo
+	// NOTE: We build cgo packages with cgoEnabled both set to true and false.
```
Comment (fmeum) [inline go/tools/builders/compilepkg.go:276]: I have a hard time fully understanding this comment, could you expand it?

File: tests/core/cgo/asm_dep_conditional_cgo/asm_dep_conditional_cgo.go (hunk 1 above)
Comment (evanj) [reply tests/core/cgo/asm_dep_conditional_cgo/asm_dep_conditional_cgo.go:1]: Oops thanks, no. Removed this and the other main program. I used them to understand/debug what was happening, then converted them into the test version.

File: go/tools/builders/compilepkg.go (hunk 4 above)
Comment (evanj) [reply go/tools/builders/compilepkg.go:276]: Great point. This is unclear to me now, a week later :)

I revised the comments on both variables to try to make this more clear. Basically the problem with assembly specifically is:

* if the package contains any cgo files, the assembler is the C compiler.
* Any package, including cgo packages, can be built with CGO_ENABLED=0 AND with CGO_ENABLED=1. When there are build constraints, this should work.

These two things are related but independent choices. Previously: disabling CGO would cause this code to revert to using Go's assembler for the .s files.

**Review by fmeum — APPROVED** [review]
