### PR TITLE
Setting comment position according to inserted import

### LINKED ISSUE #2592: Build failure in github.com/ulikunitz/xz under coverage
Bazel fails to build `@com_github_ulikunitz_xz//lzma:go_default_test` under `bazel coverage`, although it succeeds in `go test -cover`:

```bash
$ go get github.com/ulikunitz/xz
$ go test -cover github.com/ulikunitz/xz/lzma
ok  	github.com/ulikunitz/xz/lzma	2.455s	coverage: 80.6% of statements
```

### What version of rules_go are you using?

0.23.7

### What version of gazelle are you using?

0.21.1

### What version of Bazel are you using?

3.4.1

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Darwin and Linux amd 64

### What did you do?

Add the following rule to a WORKSPACE file:

```Python
go_repository(
    name = "com_github_ulikunitz_xz",
    importpath = "github.com/ulikunitz/xz",
    sum = "h1:YvTNdFzX6+W5m9msiYg/zpkSURPPtOlzbqYjrFn7Yt4=",
    version = "v0.5.7",
)
```

Run:
```bash
$ bazel coverage @com_github_ulikunitz_xz//lzma:go_default_test
```

### What did you expect to see?

Build and test succeed

### What did you see instead?

```
ERROR: /private/var/tmp/_bazel_zplin/029a80a95b282f3a98937d78e6378829/external/com_github_ulikunitz_xz/lzma/BUILD.bazel:42:8: GoCompilePkg external/com_github_ulikunitz_xz/lzma/go_default_test.internal.a failed (Exit 1) builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix darwin_amd64 -src external/com_github_ulikunitz_xz/lzma/bintree.go -src ... (remaining 151 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
compilepkg: error running subcommand: exit status 2
/private/var/tmp/_bazel_zplin/029a80a95b282f3a98937d78e6378829/sandbox/darwin-sandbox/5/execroot/__main__/external/com_github_ulikunitz_xz/lzma/bitops.go:7: syntax error: missing import path
/private/var/tmp/_bazel_zplin/029a80a95b282f3a98937d78e6378829/sandbox/darwin-sandbox/5/execroot/__main__/external/com_github_ulikunitz_xz/lzma/bitops.go:9: syntax error: non-declaration statement outside function body
Target @com_github_ulikunitz_xz//lzma:go_default_test failed to build
```

### PR DESCRIPTION
**Pull request by linzhp**
**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**

* Copying the implementation of `AddNamedImport` from golang.org/x/tools/go/ast/astutil to better handle comments.
* Added integration test to verify the fix.

**Which issues(s) does this PR fix?**

Fixes #2592

### CODE REVIEW

File: go/tools/builders/cover.go [hunk 1]
```diff
@@ -151,14 +151,18 @@ func addNamedImport(fset *token.FileSet, f *ast.File, name, path string) {
...
 	// package declaration.
-	impDecl.TokPos = f.Package
+	impDecl.TokPos = f.Name.End() + 2 // +2 for a blank line
 	file := fset.File(f.Package)
 	pkgLine := file.Line(f.Package)
+	importLength := impDecl.End() - impDecl.Pos() + 1
 	for _, c := range f.Comments {
-		if file.Line(c.Pos()) > pkgLine {
-			break
+		if file.Line(c.Pos()) <= pkgLine {
```
Comment (jayconrod) [inline go/tools/builders/cover.go:159]: I don't think I understand what's happening here to be sure whether it's correct.

It looks like there's a function in `x/tools` that does this: [`astutil.AddNamedImport`](https://github.com/golang/tools/blob/d00afeaade8f1e68fb815705aa42d704c1b6df35/go/ast/astutil/imports.go#L28). Instead of trying to fix this, let's copy that function here, along with a comment pointing to the original implementation.

File: go/tools/builders/imports.go [hunk 2]
```diff
@@ -0,0 +1,211 @@
+package main
```
Comment (jayconrod) [inline go/tools/builders/imports.go:1]: Please add a copyright notice and license. Since this is copied from x/tools, I believe it should be the notice from the origin file.
