### PR TITLE
asm: Pass package path with -p

### LINKED ISSUE #3199: Unable to build golang.org/x/sys with Go 1.19 beta1
### What version of rules_go are you using?

v0.33.0

### What version of gazelle are you using?

v0.25.0

### What version of Bazel are you using?

```
% bazel version
Build label: 5.1.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Apr 8 15:49:48 2022 (1649432988)
Build timestamp: 1649432988
Build timestamp as int: 1649432988
```

### Does this issue reproduce with the latest releases of all the above?

Yes.

### What operating system and processor architecture are you using?

```
% uname -sm
Linux x86_64
```

### What did you do?

Attempt to build a binary that imports golang.org/x/sys with Go 1.19 beta1.

### What did you expect to see?

A successful build.

### What did you see instead?

```
ERROR: /home/user/src/tmp/hello/BUILD.bazel:11:10: GoLink hello/hello_/hello failed: (Exit 1): builder failed: error executing command bazel-out/k8-opt-exec-2B5CBBC6/bin/external/go_sdk/builder link -sdk external/go_sdk -installsuffix linux_amd64 -arc ... (remaining 17 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox
2022/06/14 16:03:32 link: unlinkable object (from package golang.org/x/sys/unix) - compiler requires -p flag
link: error running subcommand external/go_sdk/pkg/tool/linux_amd64/link: exit status 1
Target //hello:hello failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

---

To reproduce, here's a copy of all files and the directory layout:

```
-- BUILD.bazel --
load("@bazel_gazelle//:def.bzl", "gazelle")

# gazelle:prefix example.com/demo
gazelle(name = "gazelle")

-- WORKSPACE --
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "685052b498b6ddfe562ca7a97736741d87916fe536623afb7da2824c0211c369",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.33.0/rules_go-v0.33.0.zip",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.33.0/rules_go-v0.33.0.zip",
    ],
)

http_archive(
    name = "bazel_gazelle",
    sha256 = "5982e5463f171da99e3bdaeff8c0f48283a7a5f396ec5282910b9e8a49c0dd7e",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.25.0/bazel-gazelle-v0.25.0.tar.gz",
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.25.0/bazel-gazelle-v0.25.0.tar.gz",
    ],
)

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")
load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies", "go_repository")

go_repository(
    name = "org_golang_x_sys",
    importpath = "golang.org/x/sys",
    sum = "h1:Zu/JngovGLVi6t2J3nmAf3AoTDwuzw85YZ3b9o4yU7s=",
    version = "v0.0.0-20220610221304-9f5ed59c137d",
)

go_rules_dependencies()

go_register_toolchains(version = "1.19beta1")

gazelle_dependencies()

# Workaround for https://github.com/bazelbuild/bazel-gazelle/issues/1217
go_repository(
    name = "org_golang_x_xerrors",
    importpath = "golang.org/x/xerrors",
    sum = "h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=",
    version = "v0.0.0-20200804184101-5ec99f83aff1",
)

-- go.mod --
module example.com/demo

go 1.18

require golang.org/x/sys v0.0.0-20220610221304-9f5ed59c137d

-- go.sum --
golang.org/x/sys v0.0.0-20220610221304-9f5ed59c137d h1:Zu/JngovGLVi6t2J3nmAf3AoTDwuzw85YZ3b9o4yU7s=
golang.org/x/sys v0.0.0-20220610221304-9f5ed59c137d/go.mod h1:oPkhp1MJrh7nUepCBck5+mAzfO9JrbApNNgaTdGDITg=

-- hello/BUILD.bazel --
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "hello_lib",
    srcs = ["hello.go"],
    importpath = "example.com/demo/hello",
    visibility = ["//visibility:private"],
    deps = ["@org_golang_x_sys//unix"],
)

go_binary(
    name = "hello",
    embed = [":hello_lib"],
    visibility = ["//visibility:public"],
)

-- hello/hello.go --
package main

import (
	"fmt"

	_ "golang.org/x/sys/unix"
)

func main() {
	fmt.Println("hello")
}
```

I got successful builds for the following cases:

- `:hello_lib`
- replace `/x/sys/unix` with a no-op local dependency `//foo:foo_lib` 
- replace `/x/sys/unix` with a simple external dependency (go.uber.org/atomic in this case)

So this is specifically an issue with how x/sys/unix is linked.

@sywhang thinks this is caused by https://github.com/golang/go/commit/e8534640557939755917edc3e6afc16d93b2e70b.

### PR DESCRIPTION
**Pull request by fmeum**
This is required to produce linkable objects as of Go 1.19.

Fixes #3199

### CODE REVIEW

File: go/tools/builders/asm.go [hunk 1]
```diff
@@ -137,9 +140,12 @@ func buildSymabisFile(goenv *env, sFiles, hFiles []fileInfo, asmhdr string) (str
 	return symabisName, err
 }
 
-func asmFile(goenv *env, srcPath string, asmFlags []string, outPath string) error {
+func asmFile(goenv *env, srcPath, packagePath string, asmFlags []string, outPath string) error {
 	args := goenv.goTool("asm")
 	args = append(args, asmFlags...)
+	if packagePath != "" {
+		args = append(args, "-p", packagePath)
+	}
```
Comment (sluongng) [inline go/tools/builders/asm.go:148]: This would make rules_go incompatible with lower version of go sdk (before 1.19) because `go tool asm` have yet to added this flag.

Do we need to do this in a separate file dedicated to 1.19?

Comment (fmeum) [reply go/tools/builders/asm.go]: Good catch. I pushed a new commit where I only add the flag with Go 1.19+. For some reason, I do get duplicate definition build errors though - I'm probably using `//go:build` wrong. Do you know how I can fix it?

**Comment by sywhang** [comment]
@abhinav is on vacation till a couple weeks later, so I took over the testing here at Uber. Can confirm that the fix works (minus the duplicate build errors part).

File: go/tools/builders/asm_go1.go [hunk 2]
```diff
@@ -0,0 +1,8 @@
+//go:build !go1.19
```
Comment (btwiuse) [inline go/tools/builders/asm_go1.go:1]: If we use pre go1.18 to build, will the `//go:build` directive still work?

**Comment by sluongng** [comment]
> For some reason, I do get duplicate definition build errors though - I'm probably using //go:build wrong. Do you know how I can fix it?

I tried to reproduce this with normal `go build` command

```
~/test> cat main.go
package main

import "fmt"

func main() {
    fmt.Println(Version)
}

~/test> cat lib_go1.go
//go:build !go1.19
// +build !go1.19

package main

var Version = "1.18"

~/test> cat lib_go119.go
//go:build go1.19
// +build go1.19

package main

var Version = "1.19"

~/test> cat go.mod
module temp

go 1.18

~/test> go version
go version go1.18.3 darwin/arm64
```

And then run this
```
~/test> GOCACHE=$(mktemp -d) go build -x .

...
/opt/homebrew/Cellar/go/1.18.3/libexec/pkg/tool/darwin_arm64/compile -o $WORK/b001/_pkg_.a -trimpath "$WORK/b001=>" -p main -lang=go1.18 -complete -buildid UPD40Vf15HmsGAFN49LI/UPD40Vf15HmsGAFN49LI -goversion go1.18.3 -shared -c=4 -nolocalimports -importcfg $WORK/b001/importcfg -pack ./lib_go1.go ./main.go
...
```

Note how `lib_go1.go` was included and not `lib_go119.go`.

So it seems like `go tool compile` is depending on `go build` to filter out the source file before hand?
And we might need to replicate that logic with rules_go?

**Comment by sluongng** [comment]
It seems like this will affect https://github.com/bazelbuild/rules_go/pull/3212 as well.

There are a few ways we can go about this:

- Build tooling to support different implementation for different goSdk versions

- Commit to a non-backward compatible upgrade

The second option seems to be a lot easier:

- Make v0.34.0 to support Go 1.18 minimum, include https://github.com/bazelbuild/rules_go/pull/3212 in the release

- Make v0.35.0 to support Go 1.19 minimum, include this PR in the release.

**Comment by sluongng** [comment]
cc: @thempatel who have been doing some work around build constraints over in Gazelle repo.

**Comment by sluongng** [comment]
I think thats the sensible solution, but I don't like it personally. 😆 
It's possible, does not means we should.

Reason is simply "additional complexity" on top of existing platform + cgo on/off matrixes.
And to support this long term, the parser inside gazelle would also need to handle this properly. (yes, we already DO have a parser, see https://github.com/bazelbuild/bazel-gazelle/pull/1243).
Between both rules_go and gazelle, the active maintainers is quite limitted so I would vote to keep it simple so that we can focus on more important things.

Imo we only need to provide a release cadence where 1 version that is backward compatible with the old GoSDK. Meaning that the moment 1.19 hits release, we can safely say that 1.17 is no longer supported and move to 1.18, then shortly move to 1.19 in the version after that, with possible cherry-pick backporting of critical bugs via patch releases.

Folks who wish to adopt latest Go version earlier (i.e. during RC releases) should have the capacity to patch rules_go with the content of this PR to make it work.

**Comment by fmeum** [comment]
Sounds reasonable to me in general.

But don't we have the special problem here that we need this change to support 1.19 but the change fails with versions before 1.19? This would be much simpler if `asm` had `-p` already in 1.18 as then we could just add support for 1.19 at the same time we drop support for 1.17.

**Comment by sluongng** [comment]
See https://github.com/bazelbuild/rules_go/wiki/Deprecation-schedule#supported-go-versions

> The Go Team provides support for the current and previous minor versions of Go. For example, if Go 1.15 is the current version, then 1.15 and 1.14 are supported. Only supported versions receive bug fixes and security updates, so users are strongly encouraged to update to those versions.
> 
> Each minor version of rules_go only supports the minor versions of Go that were supported at the time of release. rules_go may break compatibility with older versions.

So I would suggest these:

1. We remove the multi-version support and leave this PR open for now. 
2. Add a description at top guiding people on how to patch their rules_go if they wish to use 1.19 early.
3. Complete and merge https://github.com/bazelbuild/rules_go/pull/3212 and create a new release for 1.18 compatibility. In which we announce next release to be on the same date with Go 1.19 
4. When Go 1.19 get released, merge this and release a new rules_go version targeting 1.19 onward.


I would love to hear other maintainers opinion on this as well. 🤔

**Comment by fmeum** [comment]
@sywhang @sluongng I pushed a new version with a runtime check that should allow us to merge this right away. PTAL.

File: go/tools/builders/asm.go [hunk 3]
```diff
@@ -137,12 +141,34 @@ func buildSymabisFile(goenv *env, sFiles, hFiles []fileInfo, asmhdr string) (str
...
+		// Developer version or something with an unparseable version string,
+		// assume Go 1.19 or higher.
+		return true
+	}
+	minorVersion, err := strconv.Atoi(match[1])
+	if err != nil {
+		return true
+	}
+	return minorVersion >= 19
+}
```
Comment (sluongng) [inline go/tools/builders/asm.go:174]: A quick test on this approach for those who wonder "how would this work with patch versions"

```
~/test> cat main.go
package main

import (
    "fmt"
    "regexp"
    "runtime"
)

func main() {
    fmt.Println("version:", runtime.Version())

    goMinorVersionRegexp := regexp.MustCompile(`^go1\.(\d+)`)
    matches := goMinorVersionRegexp.FindStringSubmatch(runtime.Version())
    for i, m := range matches {
        fmt.Printf("match no %d: %s\n", i, m)
    }
}
~/test> go run main.go
version: go1.18.4
match no 0: go1.18
match no 1: 18
```

So it works :)

**Review by sluongng — APPROVED** [review]
Look obviously correct to me. 👍

File: go/tools/builders/asm.go (hunk 3 above)
Comment (fmeum) [reply go/tools/builders/asm.go:174]: Yeah, that's why I went with a regexp instead of simple split logic - I was worried of patch and rc/beta versions.

**Comment by martinbaillie** [comment]
Would it be possible to cut an official release that has this in it? 🙏🏻

**Comment by sywhang** [comment]
https://github.com/bazelbuild/rules_go/releases/tag/v0.34.0 has this fix in it.

**Comment by martinbaillie** [comment]
So it does. My apologies!
