### PR TITLE
Fix regression in empty `.go` file filtering for nogo

### LINKED ISSUE #3828: nogo fails using WORKSPACE.bazel after upgrade to 0.45.0
### What version of rules_go are you using?

0.45.0

### What version of gazelle are you using?

0.35.0

### What version of Bazel are you using?

```
bazel version
Build label: 7.0.0- (@non-git)
Build target: @@//src/main/java/com/google/devtools/build/lib/bazel:BazelServer
Build time: Tue Jan 1 00:00:00 1980 (315532800)
Build timestamp: 315532800
Build timestamp as int: 315532800
```

### Does this issue reproduce with the latest releases of all the above?

ya

### What operating system and processor architecture are you using?

Linux amd64

### What did you do?

Upgrade rules_go to 0.45.0 from 0.44.2.

Upon upgrading, nogo fails on things that are wrong and returns garbage output like:

```
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
compilepkg: nogo: errors found by nogo during build-time code analysis:
bazel-out/k8-fastbuild/bin/path/to/file/1437484352.go:1:1: at least one file in a package should have a package comment (ST1000)
```

Note that only the file path was replaced, not the file name. Bazel literally returns a random number here.  Downgrading to 0.44.2 makes the issue go away.

### What did you expect to see?

no nogo failures

### What did you see instead?

gibberish  nogo failures

### PR DESCRIPTION
**Pull request by fmeum**
**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**

6236dd80670cdfe1477a484e98e3f82dbcc28fe9 regressed the nogo exclusion logic for the empty `.go` file generated for targets that otherwise don't contain any `.go` files. The test had been silently disabled a while ago when the name pattern for the empty file was changed.

This is fixed by reintroducing the exclusion logic and making the test more strict.

**Which issues(s) does this PR fix?**

Fixes #3828

**Other notes for review**

### CODE REVIEW

**Comment by fmeum** [comment]
cc @sluongng

File: go/tools/builders/compilepkg.go [hunk 1]
```diff
@@ -270,16 +271,17 @@ func compileArchive(
 	// constraints.
 	compilingWithCgo := haveCgo && cgoEnabled
 
+	keepForNogo := func(s string) bool { return !ignoreForNogo[s] }
```
Comment (sluongng) [inline go/tools/builders/compilepkg.go:274]: Nit: i think you could inline the whole filterSlice func here instead of declaring a utility func + a filter func.

**Review by sluongng — APPROVED** [review]
Great fix. Thanks!

File: go/tools/builders/compilepkg.go (hunk 1 above)
Comment (fmeum) [reply go/tools/builders/compilepkg.go]: Done

File: go/tools/builders/compilepkg.go [hunk 2]
```diff
@@ -203,6 +203,7 @@ func compileArchive(
 	}
 	defer cleanup()
 
+	ignoreForNogo := make(map[string]bool)
```
Comment (sluongng) [inline go/tools/builders/compilepkg.go:206]: Sorry for not spotting this earlier, but is this a length == 1 map?
If that’s the case, could we use a simple `string` var instead?

File: go/tools/builders/compilepkg.go [hunk 3]
```diff
@@ -270,16 +271,25 @@ func compileArchive(
...
 	// goSrcsNogo and cgoSrcsNogo are copies of the original source files for nogo to run static analysis.
-	goSrcsNogo := goSrcs
+	goSrcsNogo := filterForNogo(goSrcs)
 	cgoSrcsNogo := cgoSrcs
 
 	// Instrument source files for coverage.
 	if coverMode != "" {
 		// deep copy original source files for nogo static analysis, avoid being modified by coverage.
-		goSrcsNogo = append([]string{}, goSrcs...)
+		goSrcsNogo = filterForNogo(append([]string{}, goSrcs...))
```
Comment (sluongng) [inline go/tools/builders/compilepkg.go:292]: We already filter once outside the `if` clause, let’s just re-use the result?

```suggestion
		goSrcsNogo = filterForNogo(append([]string{}, goSrcsNogo...))
```

Comment (sluongng) [reply go/tools/builders/compilepkg.go:292]: and since the filterForNogo is creating a copied slice anyway, I think we could simplify this further.

File: go/tools/builders/compilepkg.go (hunk 2 above)
Comment (linzhp) [reply go/tools/builders/compilepkg.go:206]: nit for naming: we should probably call this `emptyFiles`, just in case there are other usage of them in the future. If we need to use map as a set, we prefer `map[string]struct{}`, because map[string]bool has 3 states for every entry: true,false,absent, while map[string]struct{} only has two: present,absent, which has less ambiguity.

File: go/tools/builders/compilepkg.go (hunk 3 above)
Comment (tyler-french) [reply go/tools/builders/compilepkg.go:292]: +1, `filterForNogo` is effectively a deep copy

File: tests/core/nogo/generate/empty_test.go [hunk 4]
```diff
@@ -77,12 +75,11 @@ var Analyzer = &analysis.Analyzer{
 
 func run(pass *analysis.Pass) (interface{}, error) {
 	for _, f := range pass.Files {
-		pos := pass.Fset.PositionFor(f.Pos(), false)
-
-		if strings.HasSuffix(pos.Filename, filepath.Join(".", "_empty.go")) {
+		// Fail on any package that isn't the test's package 'simple' or 'main'.
```
Comment (tyler-french) [inline tests/core/nogo/generate/empty_test.go:78]: clarification: what is `simple`?

File: go/tools/builders/compilepkg.go (hunk 2 above)
Comment (tyler-french) [reply go/tools/builders/compilepkg.go:206]: To @sluongng's point, could we avoid needing a set when there is a maximum of one empty file? I think a `string` or `*string` would indeed

File: go/tools/builders/compilepkg.go (hunk 3 above)
Comment (fmeum) [reply go/tools/builders/compilepkg.go]: Changed this by making both deep copies unconditional, the alternative just seemed too confusing for little gain.

File: go/tools/builders/compilepkg.go [hunk 5]
```diff
@@ -270,18 +271,24 @@ func compileArchive(
 	// constraints.
 	compilingWithCgo := haveCgo && cgoEnabled
 
+	filterForNogo := func(slice []string) []string {
+		var filtered []string
```
Comment (tyler-french) [inline go/tools/builders/compilepkg.go:275]: optional, pre-allocate
```suggestion
		filtered := make([]string, 0, len(slice))
```

**Review by tyler-french — APPROVED** [review]
Tested at Uber and LGTM! Added a small optional suggestion
