### PR TITLE
Fix stdlib file outputs pointing to processwrapper

### LINKED ISSUE #3607: stdlib list json includes process sandbox output files
### What version of rules_go are you using?

0.40

### What version of gazelle are you using?

N/A

### What version of Bazel are you using?

6.2

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

linux amd64

### What did you do?

Build `@io_bazel_rules_go//:stdlib` to generate the `stdlib_list_json` file (`bazel-out/k8-fastbuild/bin/external/io_bazel_rules_go/stdlib_/stdlib.pkg.json`).

### What did you expect to see?

All stdlib packages have GoFiles that point to available files in external/.

### What did you see instead?

Some stdlib packages contain GoFiles references to non-go files in the processwrapper sandbox (which have been deleted already), eg:

```json
{"ID":"@io_bazel_rules_go//stdlib:plugin","Name":"plugin","PkgPath":"plugin","Standard":true,"GoFiles":["__BAZEL_OUTPUT_BASE__/external/go_sdk/src/plugin/plugin.go"],"CompiledGoFiles":["__BAZEL_OUTPUT_BASE__/external/go_sdk/src/plugin/plugin.go","/home/user/.cache/pkgdrv/0ddf1c72b811bee41d29991c732306ef72553747/sandbox/processwrapper-sandbox/4831/execroot/__main__/bazel-out/k8-fastbuild/bin/external/io_bazel_rules_go/stdlib_/stdlib.pkg.json.gocache/ef/efa5044179a52b97e2d30174a1ffa5381f34c2e60ca1e3b6a1609cf93e0d4de4-d","/home/user/.cache/pkgdrv/0ddf1c72b811bee41d29991c732306ef72553747/sandbox/processwrapper-sandbox/4831/execroot/__main__/bazel-out/k8-fastbuild/bin/external/io_bazel_rules_go/stdlib_/stdlib.pkg.json.gocache/d1/d108a8f510af0b01f9dba7f2a1ad25a8d6e98a3017f029d38e5c5fbed6e0580e-d","/home/user/.cache/pkgdrv/0ddf1c72b811bee41d29991c732306ef72553747/sandbox/processwrapper-sandbox/4831/execroot/__main__/bazel-out/k8-fastbuild/bin/external/io_bazel_rules_go/stdlib_/stdlib.pkg.json.gocache/92/92cd332e0a0e9e82c210a4ef1166b60055f006e0e68288a03fef6d3bcad2b1c4-d"]
```

> /home/user/.cache/pkgdrv/0ddf1c72b811bee41d29991c732306ef72553747/sandbox/processwrapper-sandbox/4831/execroot/__main__/bazel-out/k8-fastbuild/bin/external/io_bazel_rules_go/stdlib_/stdlib.pkg.json.gocache/92/92cd332e0a0e9e82c210a4ef1166b60055f006e0e68288a03fef6d3bcad2b1c4-d

### PR DESCRIPTION
**Pull request by JamyDev**
**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**

Defines an output_directory so the generated files get copied to execroot.
Make sure the path passed to GOCACHE are absolute and reverse the path back to execroot after getting the go list output

**Which issues(s) does this PR fix?**

Fixes #3607

**Other notes for review**

### CODE REVIEW

File: go/tools/builders/stdliblist.go [hunk 1]
```diff
@@ -279,12 +280,19 @@ func stdliblist(args []string) error {
 
 	encoder := json.NewEncoder(jsonFile)
 	decoder := json.NewDecoder(jsonData)
+	pathReplaceFn := func (s string) string {
+		if strings.HasPrefix(s, absCachePath) {
+			return strings.Replace(s, absCachePath, filepath.Join("__BAZEL_EXECROOT__", *cachePath), 1)
```
Comment (linzhp) [inline go/tools/builders/stdliblist.go:285]: @fmeum instead of doing this, do you think it's safe to simply find the position of "execroot" replace the whole prefix with `__BAZEL_EXECROOT__`?

**Review by linzhp — APPROVED** [review]

File: go/tools/builders/stdliblist.go (hunk 1 above)
Comment (linzhp) [reply go/tools/builders/stdliblist.go:285]: will decide later
